config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: '/api/v1/auth',
  :controllers => {sessions: 'sessions'}
  # devise_for :users, path: "account", 
  #             path_names: { 
  #               sign_in: 'login',
  #               sign_out: 'logout',
  #               password: 'recoverpwd',
  #               unlock: 'unblock',
  #               registration: 'register',
  #               sign_up: 'signup' 
  #             },
  #             :controllers => {sessions: 'sessions', registrations: 'registrations'}

  # devise_scope :user do
  #   get "account/getuserinfo", to: "registrations#getuserinfo"
  # end

  root 'static_pages#formulabook'
  
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  #get 'formulabook/index.html', :to => redirect('/formulabook/index.html')

  namespace :api do
    namespace :v1 do
      namespace :std do
        resources :units
        resources :properties, only: [:index, :create, :update, :destroy] do
          resources :units, only: [:index, :create, :update, :destroy]
        end
      end
      get 'sync'    => 'syncs#index'
      put 'sync'    => 'syncs#sync'
      put 'clean'    => 'test#clean'
      put 'unique'  => 'unique#unique?'
      resources :formulas do
        resources :variables
        resources :globals, only: [:index, :destroy]
      end
      resources :variables
      resources :globals
      resources :favorites
      resources :categories
    end 
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.testlab.herokuapp.com/">Cloud TestLab</a>
    by <a href="http://www.sangamsoftech.com/">Sangamsoftech.com</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.sangamsoftech.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<style type="text/css">
  .nav > li {
  position: relative;
  display: inline-block;
}
</style>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
          </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
      <%= yield %>